export const FETCH_COMPANIES = 'FETCH_COMPANIES';
export const UPDATE_COMPANY = 'UPDATE_COMPANY';
export const DELETE_COMPANY = 'DELETE_COMPANY';
export const CREATE_COMPANY = 'CREATE_COMPANY';

export const FETCH_COMPANY = 'FETCH_COMPANY';

export const FETCH_FUNCTIONS = 'FETCH_FUNCTIONS';
export const CREATE_FUNCTION = 'CREATE_FUNCTION';
export const DELETE_FUNCTION = 'DELETE_FUNCTION';

export const FETCH_TABLES = 'FETCH_TABLES';

export const CREATE_CALL = 'CREATE_CALL';
